### ISSUE TITLE
env page not found

### ISSUE THREAD

**Issue by qwertyBBeers** [bilalkabas/PPO-based-Autonomous-Navigation-for-Quadcopters#2]
hello i want to learn this model and env. but, your env release page wasn't found. can i get some env file?

**Comment by penguin4466** [comment]
try this url instead: https://github.com/bilalkabas/PPO-based-Autonomous-Navigation-for-Quadcopters/releases

**Comment by qwertyBBeers** [comment]
Thank you ^^
