### ISSUE TITLE
TestEnv

### ISSUE THREAD

**Issue by KeepOnCarvingHuang** [bilalkabas/PPO-based-Autonomous-Navigation-for-Quadcopters#4]
Do we need to rewrite the env_config ["TrainEnV"] in the policy run. py file we run during testing to env_config ["TestEnV"]? I didn't see TestEnv in config.yml, do I need to redefine it myself? Do I need to correspond to the holes in the UE environment in TestEnv.zip?

**Comment by bilalkabas** [comment]
Hi,

`config.yml` contains hole positions in the training environment to generate the reward which is computed by considering drone's alignment with the center of the hole. Thus, it is not necessary in test environment as testing does not involve reward computation, instead flight time without collision. You do not need to modify `policy.run` as it does not actually use `config.yml` during testing.

Sorry for the delayed answer.

**Comment by DKKHerath** [comment]
Hi 
Go to the [releases](https://github.com/bilalkabas/DQN-based-Autonomous-Navigation-for-Quadcopters/releases) and download TestEnv.zip. After downloading completed, extract it.

TestEnv.zip is not available, Kindly let me know if it is available in another place
And what should be the file path of the extracted folder

**Comment by bilalkabas** [comment]
Hi,

The links for the releases in `README.md` has been fixed. You can access to the releases via:

https://github.com/bilalkabas/PPO-based-Autonomous-Navigation-for-Quadcopters/releases/tag/v1.0.0-windows

The path of the extracted folder should not matter.
